name: Generate Storage Artifacts

on:
  workflow_dispatch

jobs:
  provide_contracts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Set contracts matrix for all matching contracts
        id: set-matrix
        working-directory: packages/contracts
        run: |
          # Collect all contracts from core and libraries
          find src/dollar/core/*.sol src/dollar/libraries/Lib*.sol -type f > contracts.txt

          # Create the formatted contracts list <file path>:<contract name>
          touch formatted_contracts.txt
          while read -r contract; do
            contract_name=$(basename "$contract" .sol)
            echo "${contract}:${contract_name}" >> formatted_contracts.txt
          done

          # Set the matrix output
          echo "matrix=$(cat formatted_contracts.txt | jq -R -s -c 'split(\"\n\")[:-1]')" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  check_storage_layout:
    needs: provide_contracts
    runs-on: ubuntu-latest
    if: ${{ needs.provide_contracts.outputs.matrix != '[]' && needs.provide_contracts.outputs.matrix != '' }}

    strategy:
      matrix:
        contract: ${{ fromJSON(needs.provide_contracts.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check For Core Contracts Storage Changes
        uses: Rubilmax/foundry-storage-check@main
        with:
          workingDirectory: packages/contracts
          contract: ${{ matrix.contract }}